# This is a basic workflow to help you get started with Actions

name: Video Server cargo clippy

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - ext-solution
  pull_request:
    types: [synchronize, opened]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  clippy:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - name: clippy
        run: cargo clippy -- -D warnings
